<<<<<<< HEAD
name: Prueba de mensaje github actions

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar hora del sistema
        run: date

      - name: Mostrar versiÃ³n de Java
        run: java --version
=======
# nombre del flujo de trabajo
name: Prueba de mensaje github actions

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar mensaje
        run: date
        run: java --version
>>>>>>> 26dc97d (Creado texto.txt 5)
